### PR TITLE
Task12 pull request for Jack Sneed

### PR DESCRIPTION
**Pull request by JackSSS**

### CODE REVIEW

**Comment by ppham** [comment]
Please fix these style errors:
```
arguments.py:22:1: E303 too many blank lines (4)
arguments.py:36:1: E303 too many blank lines (4)
arguments.py:39:57: E202 whitespace before '}'
comprehensions.py:5:5: E303 too many blank lines (2)
comprehensions.py:21:1: E303 too many blank lines (4)
comprehensions.py:37:1: E303 too many blank lines (4)
comprehensions.py:41:5: E303 too many blank lines (2)
functional.py:15:1: E303 too many blank lines (4)
functional.py:19:5: E303 too many blank lines (2)
functional.py:28:1: E303 too many blank lines (4)
functional.py:34:24: E231 missing whitespace after ','
functional.py:35:24: E231 missing whitespace after ','
```

**Comment by ppham** [comment]
In `comprehensions.py`, you can simplify this line:

```
{i: "%i" % i*2 for i in range(1, 6)}
```
to this
```
{i: i*2 for i in range(1, 6)}
```

**Comment by am0k** [comment]
Arguments.py has 2 style errors
Comprehensions.py has 3 style errors
Funtional.py has 7

Please fix them to get full credit.

**Comment by JackSSS** [comment]
Style errors corrected

**Pull request merged**
